spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    #本地
    username: root
    password: 123456
    #服务器
  #    username: pet
  #    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 20MB


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8090
  servlet:
    context-path: /Pet

logging:
  level:
    com.xmut.pet.mapper.*: debug


#本地运行

files:
  upload:
    path: src/main/resources/static/images/

  spring:
    redis:
      database: 0 # Database index used by the connection factory.
      host: localhost # Redis server host.
      port: 6379 # Redis server port.
      password:  # Login password of the redis server.
      timeout: 3000 # Connection timeout.
      lettuce:
        pool:
          max-active: 8
          max-wait: 1
          min-idle: 0
          max-idle: 8

  logging:
    level:
      com.mk: debug

#服务器
#files:
#  upload:
#    path: resource/images/